ui: mocha-tdd
browsers:
  - name: internet explorer
    version: 8..latest
  - name: microsoftedge
    version: latest
  - name: chrome
    version: [26, latest]
  - name: firefox
    version: [20, latest]
  - name: safari
    version: [5, latest]
  - name: opera
    version: [11, latest]
  - name: ipad
    version: ['7.1', latest]
  - name: iphone
    version: ['7.0', latest]
  - name: android
    version: ['4.0',latest]
