ui: mocha-tdd
browsers:
  - name: microsoftedge
    version: latest
  - name: chrome
    version: [26, latest]
  - name: firefox
    version: [20, latest]
  - name: safari
    version: [5, latest]
  - name: opera
    version: [11, latest]
  - name: internet explorer
    version: 9..latest
  - name: android
    version: ['4.0',latest]
  - name: ipad
    version: ['7.1', '9.2']
  - name: iphone
    version: ['7.0', '9.2']
